Fix crash when opening XmlDisplay for a TestGroup node
TestCentric/testcentric-gui pull request #1109
Opened 2024-09-18 05:20 UTC by rowo360

This PR closes #1105 by disabling the context menu item 'View as XML..' for all kind of GroupNodes.

Here's a screenshot:
<img src="https://github.com/user-attachments/assets/e9e2bda8-c4a5-4fcc-808b-254ee9dd1f81" width="300">

In addition, the use case must also be taken into account if the dialog is 'pinned' and the user selects some GroupNode, now.
The proposed solution keeps the dialog open, but deletes the entire content and only displays the name of the tree node in it's caption. Here's a screenshot:

<img src="https://github.com/user-attachments/assets/2561e2e6-8147-4129-81be-870316e3246c" width="500">

Actually, the context menu no longer needs to be disabled, because the Dialog can handle GroupNodes somehow now. But from my point of view it's OK to keep it disabled, as no real XML content is displayed.

2024-09-18 15:25 UTC, CharliePoole requested changes
I'd like you to look slightly deeper into this display.

You were initially confused looking at the original code, and I can see why. It's written as if everything should be a testnode. That's because this is is older code from before we allowed display of XML under the FixtureList and TestList strategies. In the NUnit strategy, every `TreeNode` tag is a `TestNode` but in general it's now an `ITestItem`. 

I'm glad you drew my attention to this. I'm thinking we should...
1. Have a `_testItem` field in place of `_testNode`.
2. Throw in `Display` if the tag is not an `ITestItem`.
3. Eliminate any other casts of the tag in the class and use the `_testItem` instead.
4. In the case of `OnTestFinished`, you should note that there can't be a ResultNode unless there was a test executed, so a cast of `_testItem` to `TestNode` must alwas succeed.

Would you first review my thinking and tell me if it makes sense? If so, I'd prefer to do it now, and get this class working once and for all. But if you'd rather merge this and come back later, feel free to argue. :-)

2024-09-18 15:25 UTC, CharliePoole commented on src/TestCentric/testcentric.gui/Dialogs/XmlDisplay.cs
> +            XmlNode fullXml = (_testNode != null) ? GetFullXml(_testNode) : null;
I'm OK to merge this, but first read my general comment about the overall use of ITestItem vs TestNode.

2024-09-18 15:25 UTC, CharliePoole commented on src/TestCentric/testcentric.gui/Presenters/TreeViewPresenter.cs
> +            _view.ViewAsXmlCommand.Enabled = !(_view?.ContextNode?.Tag is TestGroup);
I agree with your comment that this is no longer needed so long as we display something for categories, etc.

2024-09-18 20:32 UTC, rowo360 commented
That's fine, I can continue to work on this and improve the code.
I have two questions regarding your suggestions:
- the new field `_testItem` will be of type ITestItem, right?
- Yes, I think we'll not have any casts for the Tag anymore. But I expect that we still need a cast of the `_testItem` to TestNode. At least before calling method GetFullXml() (or inside that method) and in the OnTestFinished() method. But that's ok, isn't it?

2024-09-18 20:44 UTC, rowo360 commented
I forgot to comment on point no 4: 
Can the _testItem here not be a TestNode after all? Imagine I 'pinned' the dialog and select a TestGroup. Now the _testItem is not a TestNode, but I can start a test run and the OnTestFinished() method gets invoked.

2024-09-18 23:05 UTC, CharliePoole commented
Yes, `private ITestItem _testItem` and the arg to Display would be ITestItem, because that's the most we can guarantee.

Yes, the Tag is an `object` so I think we should cast it to a known type (`ITestItem`) only once. Currently, there are two methods needing a Testode, `Display` and `OnTestFinished` they would have to cast _testItem. I think `GetFullXml` should continue to get TestNode because that's what it needs and it should only be called if we have one. Type safety makes things cleaner.

You're right about point #4. You need a cast. But there's nothing to do if it's not a `TestNode`.

2024-09-19 11:08 UTC, CharliePoole approved these changes
Thanks for reworking this. Only thing I noticed is that you left in the code in TreeViewPresenter to disable the menu item for non-testnodes. You had commented that we no longer needed to disable it and I agree. But I'm OK either way. If you make that change, just merge if GitHub lets you. Otherwise, I'll re-approve. (I always see a checkbox, which allows me to override the approval rules, but that may be because I'm the owner.)

2024-09-19 11:08 UTC, CharliePoole commented on src/TestCentric/testcentric.gui/Presenters/TreeViewPresenter.cs
> +            _view.ViewAsXmlCommand.Enabled = !(_view?.ContextNode?.Tag is TestGroup);
Weren't you going to remove this?

2024-09-19 16:19 UTC, rowo360 commented
That's right, I haven't done that yet! But I've made up for it now!
So I rollbacked that changes regarding enabling/disabling the context menu item, so that the 'View as XML..:' is always enabled again.
BTW: A NullCheck has been cheated into this commit, which was intended for later. But I hope that this kind of check is not critical.
I will do the merge, now.

2024-09-19 16:20 UTC, merged

2024-09-19 16:38 UTC, CharliePoole commented
Great! In addition, this verifies you have all the github superpowers you need. :-)