Fix crash when 'run selected tests' but no tests are selected
TestCentric/testcentric-gui pull request #1139
Opened 2024-10-13 07:18 UTC by rowo360

This PR fixes issue #1138.

Unfortunately I didn't manage to detect the actual root cause of this crash. As described in the issue repeating the same steps which were previously causing the crash suddently work. That doesn't feel good, but I'd rather fix the problem now than keep looking for a long time.

So the property `SelectedTests` might be set to null in some scenarios, which will cause the crash when executing 'Run selected tests'. Therefore I propose to fix it simply by handling this case now.

2024-10-14 20:21 UTC, CharliePoole requested changes
I can see that a test selection must  be capable of being empty but it doesn't seem to me that we should  be calling the model with an empty selection.

Additionally, if no tests are selected, it seems like the controls and menu items used to run selected tests should be disabled.

2024-10-14 20:21 UTC, CharliePoole commented on src/TestCentric/testcentric.gui/Presenters/TestCentricPresenter.cs
> +                _model.RunTests(testSelection);
How are we able to get here if there are no selected tests? While I agree that the code should check for null or empty on general principle, the overall strategy in the UI has been to disable any controls that are not usable at a given point in time. So, if there are no selected tests,  this code ought to be unreachable.

2024-10-15 12:20 UTC, rowo360 commented
That idea is even better: disable the toolbar item if no tests are selected! I like it!
I prepared a solution for this idea and added a new commit.
Basically I introduced a new event `SelectedTestsChanged` in the model. This event gets fired whenever some nodes are checked or selected in the tree and the TreeViewPresenter updates the `SelectedTests` property. The TestCentricPresenter class listens to this event and updates the enable state of the toolbar item accordingly.

Here are some screenshots to get a better impression:
In the first image the toolbar button is disabled because no node is checked, in the second image a node is checked and thus the toolbar button is enabled. The last image is without the option 'Show checkboxes' - in that case the toolbar button is always enabled - I didn't notice a scenario in which no node is selected.

<img src="https://github.com/user-attachments/assets/6f126b43-a23f-469c-8659-0f5a9791cf79" width="900">

2024-10-15 12:28 UTC, rowo360 commented
While working on this issue I wondered if the toolbar tooltip is always accurate?
The tooltip states 'Run selected tests' - but wouldn't it be more accurate to state 'Run checked tests' when the checkboxes are shown in the tree? If no checkboxes are shown, we can continue to use 'Run selected tests' as the tooltip. 
That might be helpful to understand why the toolbar button is disabled.

2024-10-15 18:57 UTC, CharliePoole commented
In my mind, when I first did this "selected" meant highlighted OR checked when checks are enabled. I agree with you that this might be confusing to the user. However, I think there are actually three states here, not two, in the way it is implemented.

1. If no checkboxes are shown, selected means selected, i.e. highlighted.
2. If checkboxes are shown _and nothing is checked_ it still means the same thing.
3. if checkboxes are shown and one or more tests are checked, then "selected" means checked.

I suggest you first verify that it works as I say, especially the second condition. If it does, then I think you would change the language in the tooltip each time it displays based on whether anything is checked rather than whether checkboxes are shown.

2024-10-15 18:59 UTC, CharliePoole commented
Is a new event needed? I'm pretty sure we were already responding to changed selection. It might be a generic property change to our settings.

2024-10-15 19:22 UTC, CharliePoole approved these changes
Looks good to me. Thanks!

My one inline comment is at your option. If you want to change the tooltip, feel free to add another commit but check out my general comment about it first.

2024-10-15 19:22 UTC, CharliePoole commented on src/TestCentric/testcentric.gui/Presenters/TestCentricPresenter.cs
> +
Will it let you use `_model.SelectedTests?.Any()` here>

2024-10-16 18:28 UTC, rowo360 commented on src/TestCentric/testcentric.gui/Presenters/TestCentricPresenter.cs
> +
Unfortunately that's rejected by the c# compiler: 
Operator '&&' cannot be applied to operands of type 'bool' and 'bool?'

2024-10-16 18:52 UTC, rowo360 commented
> Is a new event needed? I'm pretty sure we were already responding to changed selection. It might be a generic property change to our settings.

Yes indeed, there's already a similar event: the model has a property ActiveTestItem and any change of this property triggers a SelectedItemChanged event. The ActiveTestItem is set by the TreeViewPresenter whenever the selected tree node changes. But checking/unchecking tree nodes will not change the tree node selection and thus not change the ActiveTestItem. But instead only the `SelectedTests` property of the model is updated. So, I added this missing event to the `SelectedTests` property to comply to the pattern.
BTW: there's also no setting change event while checking/unchecking tree nodes

2024-10-16 19:35 UTC, merged

2024-10-16 21:57 UTC, CharliePoole commented
FYI, once you merge the branch is pretty useless so you can delete it.